import { describe, expect, test } from './harness';
import {
  ADVISORY_FEED_FILE,
  VULNERABLE_DEPENDENCY_RULE,
  auditSummary,
  dependencyFindings,
  packageOf,
  parseAdvisoryFeed,
  parseAuditNotes,
  parseDeclaredDependencies,
  parseLockFile,
  parseVersion,
  renderAdvisoryFeed,
  resolveDependencies,
  upgradeCommandFor,
} from '../src/renderer/security/advisories';
import { buildSecurityArgs, type SecurityFinding } from '../src/renderer/security/findings';

/** The lockfile exactly as `PackageLockFile.Render()` writes it. */
const REAL_LOCK = `# Generated by zornux. Do not edit by hand.

package Greetings
version = 1.0.0
source = store
hash = abc123

package Utils
version = 2.5.0
source = zornux
hash = def456
`;

const REAL_PROJECT = `name = demo
version = 1.0.0
entry = src/main.zx

dependency Greetings = ^1.0.0
dependency Utils = >=2.0.0 from store
`;

/** A feed in the COMPILER's schema (`FileDependencyAdvisorySource.AdvisoryJson`). */
const REAL_FEED = JSON.stringify({
  advisories: [
    {
      package: 'Greetings',
      affected: '<1.2.0',
      severity: 'Error',
      id: 'CVE-2026-0001',
      summary: 'A parsing flaw allows a crash.',
      url: 'https://zornux.dev/advisories/CVE-2026-0001',
      fixed: '1.2.0',
    },
  ],
});

/** A real ZX3709 finding, captured from `zornux check --security --advisories` on rc.4. */
function vulnerability(overrides: Partial<SecurityFinding> = {}): SecurityFinding {
  return {
    code: 'ZX3709',
    category: 'dependency',
    severity: 'Error',
    confidence: 'High',
    message: "'Greetings' 1.0.0 has a known vulnerability (CVE-2026-0001).",
    explanation: 'A parsing flaw allows a crash. The advisory covers <1.2.0, and the project resolved 1.0.0, which is affected.',
    suggestedFix: "Upgrade 'Greetings' to 1.2.0 or later, then re-resolve the lockfile.",
    documentationUrl: 'https://zornux.dev/advisories/CVE-2026-0001',
    file: 'app.zx',
    startLine: 1,
    startColumn: 1,
    endLine: 1,
    endColumn: 1,
    related: [],
    ...overrides,
  };
}

function codeFinding(): SecurityFinding {
  return { ...vulnerability(), code: 'ZX3701', category: 'secrets', severity: 'Critical', message: 'A secret is in the source.' };
}

describe('buildSecurityArgs with an advisory feed', () => {
  test('without a feed the invocation is unchanged, and ZX3709 never runs', () => {
    expect(buildSecurityArgs('app.zx')).toEqual(['check', 'app.zx', '--security', '--json']);
  });

  test('a feed is passed to the compiler, which does the matching', () => {
    expect(buildSecurityArgs('app.zx', true, 'C:\\ws\\zornux.advisories.json')).toEqual([
      'check',
      'app.zx',
      '--security',
      '--advisories',
      'C:\\ws\\zornux.advisories.json',
      '--json',
    ]);
  });

  test('a null feed is treated as no feed', () => {
    expect(buildSecurityArgs('app.zx', true, null)).toEqual(['check', 'app.zx', '--security', '--json']);
  });

  test('the feed file name is the one the panel looks for', () => {
    expect(ADVISORY_FEED_FILE).toBe('zornux.advisories.json');
  });
});

describe('parseAdvisoryFeed (the compiler’s schema)', () => {
  test('reads package, affected, severity, id, summary, url and fixed', () => {
    const [advisory] = parseAdvisoryFeed(REAL_FEED);
    expect(advisory.package).toBe('Greetings');
    expect(advisory.affected).toBe('<1.2.0');
    expect(advisory.id).toBe('CVE-2026-0001');
    expect(advisory.fixed).toBe('1.2.0');
  });

  test('property names match case-insensitively, as System.Text.Json does', () => {
    const [advisory] = parseAdvisoryFeed(JSON.stringify({ advisories: [{ Package: 'X', Affected: '<1.0.0', Id: 'A' }] }));
    expect(advisory.package).toBe('X');
    expect(advisory.affected).toBe('<1.0.0');
  });

  test('an entry with no package or no affected range is dropped', () => {
    expect(parseAdvisoryFeed(JSON.stringify({ advisories: [{ package: 'X' }, { affected: '<1.0.0' }] }))).toHaveLength(0);
  });

  test('a missing fixed version is null, never invented', () => {
    expect(parseAdvisoryFeed(JSON.stringify({ advisories: [{ package: 'X', affected: '<1.0.0' }] }))[0].fixed).toBeNull();
  });

  test('invalid json is an empty feed, not a throw', () => {
    expect(parseAdvisoryFeed('{{{')).toHaveLength(0);
  });

  test('a bare array is NOT the compiler’s schema and yields nothing', () => {
    expect(parseAdvisoryFeed(JSON.stringify([{ package: 'X', affected: '<1.0.0' }]))).toHaveLength(0);
  });

  test('render round-trips through the parser', () => {
    expect(parseAdvisoryFeed(renderAdvisoryFeed(parseAdvisoryFeed(REAL_FEED)))).toEqual(parseAdvisoryFeed(REAL_FEED));
  });
});

describe('parseAuditNotes (the CLI writes these to stderr)', () => {
  test('an unaudited package is named, because it is not a safe one', () => {
    const notes = parseAuditNotes(
      "note: 'Greetings' has no 'zornux.lock' entry, so its version is unknown - it was not audited for advisories, not judged safe. Run 'zornux restore' first.",
    );
    expect(notes.unaudited).toEqual(['Greetings']);
  });

  test('an advisory the compiler could not use is reported as a problem', () => {
    const notes = parseAuditNotes("warning: advisory 'CVE-1' for 'X' has an affected range '< 1.2.0' I couldn't parse - it matched nothing.");
    expect(notes.problems).toHaveLength(1);
    expect(notes.problems[0]).toContain("couldn't parse");
  });

  test('several notes across one run are all collected', () => {
    const notes = parseAuditNotes(
      ["note: 'A' has no 'zornux.lock' entry, so its version is unknown", "note: 'B' has no 'zornux.lock' entry, so its version is unknown"].join('\n'),
    );
    expect(notes.unaudited).toEqual(['A', 'B']);
  });

  test('ordinary output produces no notes', () => {
    expect(parseAuditNotes('{"findings": []}')).toEqual({ unaudited: [], problems: [] });
  });
});

describe('dependencyFindings', () => {
  test('picks out exactly the ZX3709 findings the compiler emitted', () => {
    expect(dependencyFindings([codeFinding(), vulnerability()])).toHaveLength(1);
    expect(VULNERABLE_DEPENDENCY_RULE).toBe('ZX3709');
  });

  test('a scan with no advisories has no dependency findings', () => {
    expect(dependencyFindings([codeFinding()])).toHaveLength(0);
  });
});

describe('packageOf and upgradeCommandFor', () => {
  test('the package is read out of the message the compiler wrote', () => {
    expect(packageOf(vulnerability())).toBe('Greetings');
  });

  test('the upgrade command is read out of the compiler’s suggested fix, never reconstructed', () => {
    expect(upgradeCommandFor(vulnerability())).toBe('zornux add Greetings@1.2.0');
  });

  test('an advisory with no fixed version yields no command instead of inventing one', () => {
    const noFix = vulnerability({ suggestedFix: "No fixed version is published yet; avoid the affected feature of 'Greetings'." });
    expect(upgradeCommandFor(noFix)).toBeNull();
  });
});

describe('parseLockFile', () => {
  test('reads the real rendered lockfile', () => {
    const entries = parseLockFile(REAL_LOCK);
    expect(entries).toHaveLength(2);
    expect(entries[0]).toEqual({ name: 'Greetings', version: '1.0.0', source: 'store', hash: 'abc123' });
  });
  test('an entry with an unparseable version is dropped', () => {
    expect(parseLockFile('package Bad\nversion = latest\n')).toHaveLength(0);
  });
  test('parseVersion demands a strict major.minor.patch', () => {
    expect(parseVersion('1.2.3')).toEqual({ major: 1, minor: 2, patch: 3 });
    expect(parseVersion('1.2')).toBeNull();
  });
});

describe('parseDeclaredDependencies', () => {
  test('reads name, constraint, registry and the line it is written on', () => {
    const dependencies = parseDeclaredDependencies(REAL_PROJECT);
    expect(dependencies).toHaveLength(2);
    expect(dependencies[0]).toEqual({ name: 'Greetings', constraint: '^1.0.0', registry: undefined, line: 5 });
    expect(dependencies[1].registry).toBe('store');
  });
});

describe('resolveDependencies (display only)', () => {
  test('joins declarations to the versions the lockfile pinned', () => {
    const resolved = resolveDependencies(parseDeclaredDependencies(REAL_PROJECT), parseLockFile(REAL_LOCK));
    expect(resolved[0].version).toBe('1.0.0');
    expect(resolved[1].version).toBe('2.5.0');
  });

  test('a dependency absent from the lockfile is unresolved, not assumed', () => {
    expect(resolveDependencies(parseDeclaredDependencies(REAL_PROJECT), [])[0].version).toBeNull();
  });

  test('names match case-insensitively', () => {
    expect(resolveDependencies([{ name: 'greetings', constraint: '^1.0.0', line: 1 }], parseLockFile(REAL_LOCK))[0].version).toBe('1.0.0');
  });
});

describe('auditSummary', () => {
  const dependencies = resolveDependencies(parseDeclaredDependencies(REAL_PROJECT), parseLockFile(REAL_LOCK));

  test('counts declared dependencies, vulnerable packages, blockers and fixables', () => {
    const summary = auditSummary(dependencies, [codeFinding(), vulnerability()], { unaudited: [], problems: [] });
    expect(summary).toEqual({ dependencies: 2, unaudited: 0, vulnerable: 1, blocking: 1, fixable: 1 });
  });

  test('unaudited packages come from the compiler’s notes, and are counted separately from clean ones', () => {
    const summary = auditSummary(dependencies, [], { unaudited: ['Greetings'], problems: [] });
    expect(summary.unaudited).toBe(1);
    expect(summary.vulnerable).toBe(0);
  });

  test('a warning-severity advisory does not block the build', () => {
    const summary = auditSummary(dependencies, [vulnerability({ severity: 'Warning' })], { unaudited: [], problems: [] });
    expect(summary.blocking).toBe(0);
  });

  test('a critical advisory does', () => {
    const summary = auditSummary(dependencies, [vulnerability({ severity: 'Critical' })], { unaudited: [], problems: [] });
    expect(summary.blocking).toBe(1);
  });

  test('two advisories against one package count it once as vulnerable', () => {
    const summary = auditSummary(
      dependencies,
      [vulnerability(), vulnerability({ message: "'Greetings' 1.0.0 has a known vulnerability (CVE-2026-0002)." })],
      { unaudited: [], problems: [] },
    );
    expect(summary.vulnerable).toBe(1);
    expect(summary.blocking).toBe(2);
  });
});
