import type { DeploymentContext } from '../core/Contracts';
import { imageTag } from './docker';

/**
 * CI/CD pipeline generation (Phase 13E). Pure: renders a GitHub Actions or GitLab
 * CI workflow that installs the Zornux toolchain, builds, and tests the project
 * (with an optional Docker image build). YAML is hand-written and unit-tested.
 */

export type CiProviderId = 'github' | 'gitlab';

export interface CiProviderDescriptor {
  id: CiProviderId;
  label: string;
  filename: string;
}

export const CI_PROVIDERS: readonly CiProviderDescriptor[] = [
  { id: 'github', label: 'GitHub Actions', filename: '.github/workflows/ci.yml' },
  { id: 'gitlab', label: 'GitLab CI', filename: '.gitlab-ci.yml' },
];

export function describeCiProvider(id: CiProviderId): CiProviderDescriptor {
  return CI_PROVIDERS.find((p) => p.id === id) ?? CI_PROVIDERS[0];
}

function githubActions(context: DeploymentContext): string {
  const dockerJob = context.registry
    ? `
  docker:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
      - name: Build image
        run: docker build -t ${imageTag(context)} .
`
    : '';
  return `# Generated by ZnxStudio for ${context.projectName}
name: CI
on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Zornux
        run: |
          curl -fsSL https://zornux.dev/install.sh | sh
          echo "$HOME/.zornux/bin" >> "$GITHUB_PATH"
      - name: Build
        run: zornux build
      - name: Test
        run: zornux test
${dockerJob}`;
}

function gitlabCi(context: DeploymentContext): string {
  return `# Generated by ZnxStudio for ${context.projectName}
stages:
  - build
  - test

default:
  image: debian:bookworm-slim
  before_script:
    - apt-get update && apt-get install -y --no-install-recommends curl ca-certificates
    - curl -fsSL https://zornux.dev/install.sh | sh
    - export PATH="$HOME/.zornux/bin:$PATH"

build:
  stage: build
  script:
    - zornux build

test:
  stage: test
  script:
    - zornux test
`;
}

/** Generate a CI workflow for the provider. */
export function generateCiWorkflow(id: CiProviderId, context: DeploymentContext): { filename: string; content: string } {
  const descriptor = describeCiProvider(id);
  const content = id === 'gitlab' ? gitlabCi(context) : githubActions(context);
  return { filename: descriptor.filename, content };
}
