import type { DeploymentContext } from '../core/Contracts';
import { imageTag } from './docker';
import { k8sName } from './kubernetes';

/**
 * Cloud providers (Phase 13D). Vendor-neutral, mirroring the Phase 10 AI design:
 * a provider registry (Fly / Render / Railway / AWS App Runner / GCP Cloud Run /
 * Azure Container Apps / custom, or none), a per-provider config-file generator,
 * and a deploy-command builder. No single cloud is a dependency; the provider is
 * a runtime choice in settings. All pure + unit-tested.
 */

export type CloudProviderId =
  | 'none'
  | 'fly'
  | 'render'
  | 'railway'
  | 'aws'
  | 'gcp'
  | 'azure'
  | 'custom';

export interface CloudProviderDescriptor {
  id: CloudProviderId;
  label: string;
  blurb: string;
  /** The CLI used to deploy (via tool:exec), or null for git-push / manual. */
  cli: string | null;
  /** The config file this provider generates, or null. */
  configFile: string | null;
}

export const CLOUD_PROVIDERS: readonly CloudProviderDescriptor[] = [
  { id: 'none', label: 'None', blurb: 'No cloud provider configured.', cli: null, configFile: null },
  { id: 'fly', label: 'Fly.io', blurb: 'Global app platform (flyctl).', cli: 'flyctl', configFile: 'fly.toml' },
  { id: 'render', label: 'Render', blurb: 'Git-push deploys via a Blueprint.', cli: null, configFile: 'render.yaml' },
  { id: 'railway', label: 'Railway', blurb: 'Deploy from a Dockerfile (railway CLI).', cli: 'railway', configFile: 'railway.json' },
  { id: 'aws', label: 'AWS App Runner', blurb: 'Container service on AWS.', cli: 'aws', configFile: 'apprunner.yaml' },
  { id: 'gcp', label: 'Google Cloud Run', blurb: 'Serverless containers (gcloud).', cli: 'gcloud', configFile: null },
  { id: 'azure', label: 'Azure Container Apps', blurb: 'Managed containers (az).', cli: 'az', configFile: null },
  { id: 'custom', label: 'Custom', blurb: 'Your own script / registry push.', cli: null, configFile: null },
];

export function describeCloudProvider(id: CloudProviderId): CloudProviderDescriptor {
  return CLOUD_PROVIDERS.find((p) => p.id === id) ?? CLOUD_PROVIDERS[0];
}

/** Generate the provider's config file content, or null when it has none. */
export function generateProviderConfig(id: CloudProviderId, context: DeploymentContext): { filename: string; content: string } | null {
  const name = k8sName(context);
  const image = imageTag(context);
  switch (id) {
    case 'fly':
      return {
        filename: 'fly.toml',
        content: `# fly.toml — generated by ZnxStudio for ${context.projectName}
app = "${name}"
primary_region = "iad"

[build]
  dockerfile = "Dockerfile"

[http_service]
  internal_port = ${context.port}
  force_https = true
  auto_stop_machines = true
  min_machines_running = 1

[env]
  ZORNUX_ENV = "${context.environment}"
`,
      };
    case 'render':
      return {
        filename: 'render.yaml',
        content: `# render.yaml — generated by ZnxStudio for ${context.projectName}
services:
  - type: web
    name: ${name}
    runtime: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: ZORNUX_ENV
        value: ${context.environment}
`,
      };
    case 'railway':
      return {
        filename: 'railway.json',
        content: `${JSON.stringify(
          {
            $schema: 'https://railway.app/railway.schema.json',
            build: { builder: 'DOCKERFILE', dockerfilePath: 'Dockerfile' },
            deploy: { startCommand: `zornux run ${context.entry}`, restartPolicyType: 'ON_FAILURE' },
          },
          null,
          2,
        )}\n`,
      };
    case 'aws':
      return {
        filename: 'apprunner.yaml',
        content: `# apprunner.yaml — generated by ZnxStudio for ${context.projectName}
version: 1.0
runtime: docker
build:
  commands:
    build:
      - echo "Built via Dockerfile"
run:
  runtime-version: latest
  command: zornux run ${context.entry}
  network:
    port: ${context.port}
  env:
    - name: ZORNUX_ENV
      value: "${context.environment}"
`,
      };
    default:
      return null;
  }
}

export interface DeployCommand {
  tool: string;
  args: string[];
}

/** The CLI deploy command for a provider, or null (git-push / manual). */
export function buildDeployCommand(id: CloudProviderId, context: DeploymentContext): DeployCommand | null {
  const name = k8sName(context);
  const image = imageTag(context);
  switch (id) {
    case 'fly':
      return { tool: 'flyctl', args: ['deploy'] };
    case 'railway':
      return { tool: 'railway', args: ['up'] };
    case 'gcp':
      return {
        tool: 'gcloud',
        args: ['run', 'deploy', name, '--image', image, '--port', String(context.port), '--allow-unauthenticated', '--region', 'us-central1'],
      };
    case 'azure':
      return {
        tool: 'az',
        args: ['containerapp', 'up', '--name', name, '--image', image, '--target-port', String(context.port), '--ingress', 'external'],
      };
    default:
      return null;
  }
}

/** Render a deploy command as a copy-pasteable shell string. */
export function formatDeployCommand(command: DeployCommand): string {
  return [command.tool, ...command.args.map((a) => (a.includes(' ') ? `"${a}"` : a))].join(' ');
}
