import type { DeploymentContext } from '../core/Contracts';

/**
 * Docker artifact generation (Phase 13B). Pure: renders a multi-stage Dockerfile
 * and a .dockerignore for a Zornux project from the deployment context, and
 * parses `docker ps` / `docker images` output. The module previews + saves; the
 * optional `docker` CLI (via tool:exec) lists running state.
 */

function envLines(envVars: Record<string, string>): string {
  const keys = Object.keys(envVars);
  if (keys.length === 0) return '';
  return keys.map((key) => `ENV ${key}=${JSON.stringify(envVars[key])}`).join('\n') + '\n';
}

/** Generate a multi-stage Dockerfile for the project. */
export function generateDockerfile(context: DeploymentContext): string {
  const env = envLines(context.envVars);
  return `# syntax=docker/dockerfile:1
# Generated by ZnxStudio for ${context.projectName} (${context.environment})

# ---- build stage: compile with the Zornux toolchain ----
FROM debian:bookworm-slim AS build
WORKDIR /app
RUN apt-get update \\
    && apt-get install -y --no-install-recommends curl ca-certificates \\
    && curl -fsSL https://zornux.dev/install.sh | sh \\
    && rm -rf /var/lib/apt/lists/*
ENV PATH="/root/.zornux/bin:\${PATH}"
COPY . .
RUN zornux build

# ---- runtime stage ----
FROM debian:bookworm-slim AS runtime
WORKDIR /app
RUN apt-get update \\
    && apt-get install -y --no-install-recommends ca-certificates \\
    && rm -rf /var/lib/apt/lists/*
COPY --from=build /root/.zornux /root/.zornux
COPY --from=build /app /app
ENV PATH="/root/.zornux/bin:\${PATH}"
ENV ZORNUX_ENV=${context.environment}
${env}EXPOSE ${context.port}
CMD ["zornux", "run", "${context.entry}"]
`;
}

/** Generate a .dockerignore that keeps build context small. */
export function generateDockerignore(): string {
  return `.git
.gitignore
.github
.znxstudio
dist
build
node_modules
*.zxbc
*.log
.env
.DS_Store
Dockerfile
.dockerignore
`;
}

export interface DockerContainer {
  id: string;
  image: string;
  status: string;
  name: string;
}

/** Parse `docker ps --format "{{.ID}}\t{{.Image}}\t{{.Status}}\t{{.Names}}"`. */
export function parseDockerPs(output: string): DockerContainer[] {
  const rows: DockerContainer[] = [];
  for (const line of output.split('\n')) {
    if (!line.trim()) continue;
    const [id, image, status, name] = line.split('\t');
    if (!id) continue;
    rows.push({ id, image: image ?? '', status: status ?? '', name: name ?? '' });
  }
  return rows;
}

export interface DockerImage {
  repository: string;
  tag: string;
  id: string;
  size: string;
}

/** Parse `docker images --format "{{.Repository}}\t{{.Tag}}\t{{.ID}}\t{{.Size}}"`. */
export function parseDockerImages(output: string): DockerImage[] {
  const rows: DockerImage[] = [];
  for (const line of output.split('\n')) {
    if (!line.trim()) continue;
    const [repository, tag, id, size] = line.split('\t');
    if (!repository) continue;
    rows.push({ repository, tag: tag ?? '', id: id ?? '', size: size ?? '' });
  }
  return rows;
}

/** A Docker-repository-safe name (lowercase, no spaces). */
function safeName(name: string): string {
  return name.toLowerCase().replace(/[^a-z0-9._-]+/g, '-').replace(/^[-.]+|[-.]+$/g, '') || 'app';
}

/** The image tag for the project, honoring an optional registry prefix. */
export function imageTag(context: DeploymentContext): string {
  const tag = context.environment === 'production' ? 'latest' : context.environment;
  const base = `${safeName(context.projectName)}:${tag}`;
  return context.registry ? `${context.registry.replace(/\/+$/, '')}/${base}` : base;
}
