import type { DeploymentContext } from '../core/Contracts';
import { imageTag } from './docker';

/**
 * Kubernetes artifact generation (Phase 13C). Pure: renders a Deployment +
 * Service manifest (multi-doc YAML) for the project, and parses `kubectl get`
 * table output. YAML is hand-written (no dependency) and unit-tested.
 */

/** A DNS-1123-safe name derived from the project. */
export function k8sName(context: DeploymentContext): string {
  return context.projectName.toLowerCase().replace(/[^a-z0-9-]+/g, '-').replace(/^-+|-+$/g, '') || 'app';
}

function envBlock(envVars: Record<string, string>, indent: string): string {
  const keys = Object.keys(envVars);
  if (keys.length === 0) return '';
  const lines = keys.map((key) => `${indent}- name: ${key}\n${indent}  value: ${JSON.stringify(envVars[key])}`);
  return `${indent.slice(0, -2)}env:\n${lines.join('\n')}\n`;
}

/** Generate Deployment + Service manifests as one multi-document YAML string. */
export function generateManifests(context: DeploymentContext): string {
  const name = k8sName(context);
  const image = imageTag(context);
  const replicas = context.environment === 'production' ? 2 : 1;
  const env = envBlock(context.envVars, '            ');
  return `# Generated by ZnxStudio for ${context.projectName} (${context.environment})
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${name}
  labels:
    app: ${name}
spec:
  replicas: ${replicas}
  selector:
    matchLabels:
      app: ${name}
  template:
    metadata:
      labels:
        app: ${name}
    spec:
      containers:
        - name: ${name}
          image: ${image}
          ports:
            - containerPort: ${context.port}
${env}          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: ${name}
  labels:
    app: ${name}
spec:
  selector:
    app: ${name}
  ports:
    - port: 80
      targetPort: ${context.port}
  type: ClusterIP
`;
}

export interface KubeResource {
  name: string;
  ready: string;
  status: string;
  restarts: string;
  age: string;
}

/** Parse a `kubectl get pods` table (whitespace columns, header skipped). */
export function parseKubectlGet(output: string): KubeResource[] {
  const rows: KubeResource[] = [];
  const lines = output.split('\n');
  for (const line of lines) {
    if (!line.trim()) continue;
    const cols = line.trim().split(/\s+/);
    if (cols[0] === 'NAME') continue;
    if (cols.length < 3) continue;
    rows.push({
      name: cols[0],
      ready: cols[1],
      status: cols[2],
      restarts: cols[3] ?? '',
      age: cols[4] ?? '',
    });
  }
  return rows;
}
